version: "3.9"

services:
  mysql-orders:
    image: mysql:8.0
    container_name: mysql-orders
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders_api
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      
      - "3308:3306"
    volumes:
      - orders_db_data:/var/lib/mysql
    networks:
      - orders-net

  adminer:
    image: adminer
    container_name: adminer-orders
    restart: unless-stopped
    ports:
      
      - "8082:8080"
    networks:
      - orders-net

volumes:
  orders_db_data:

networks:
  orders-net:
