version: "3.9"

services:
  mysql-book-review:
    image: mysql:8.0
    container_name: mysql-book-review
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel-10-book-review
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      # Usamos 3307 en tu m√°quina para no chocar con el 3306 de Laragon
      - "3307:3306"
    volumes:
      - book_review_db_data:/var/lib/mysql
    networks:
      - book-review-net

  adminer:
    image: adminer
    container_name: adminer-book-review
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - book-review-net

volumes:
  book_review_db_data:

networks:
  book-review-net: